'use client';

import React, { useEffect, useMemo } from 'react';
import { X, ShieldAlert, ShieldCheck } from 'lucide-react';
import type { XdfDefinition } from '@tsunagi/xdf-engine';
import { calibrationSector, collateralOf, preflight, type FlashPlan } from '@tsunagi/ds2-smg2-write';
import { C } from '@/lib/chrome';
import { useLang } from '@/lib/i18n';
import { LABEL, MicroLabel, Pill, TextButton } from '@/components/ui';

/**
 * What would happen if this were written to the ECU, and what stops it.
 *
 * ## Why this exists in a build that cannot write
 *
 * `CAPABILITIES.canWriteToEcu` is false and the button below is never armed. That is not a
 * reason to hide the surface — it is the reason to show it. Everything about a flash is decided
 * before the first telegram: whether the image came off *this* ECU, whether the checksum is
 * right, whether a byte changed that no edit accounts for, whether there is a backup. All of
 * that is computed and shown here, today, against the workspace in hand.
 *
 * So an operator can see exactly how close a write is, and exactly what the remaining obstacle
 * is, rather than meeting a greyed-out button with no explanation. The list is generated by
 * `preflight` — the same function a real write would have to satisfy — so it cannot drift away
 * from the gate it describes.
 *
 * ## The shape
 *
 * φ, like every other window in this system: the height follows the width. Findings are a list
 * because they are a list; the one that currently blocks is not styled differently from the ones
 * that would, because which check fails is a fact about today rather than a property of the check.
 */
export function FlashDialog({
    plan,
    definition,
    onClose,
}: {
    plan: FlashPlan;
    definition: XdfDefinition;
    onClose: () => void;
}) {
    const { t } = useLang();

    useEffect(() => {
        const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
        window.addEventListener('keydown', onKey);
        return () => window.removeEventListener('keydown', onKey);
    }, [onClose]);

    const result = useMemo(() => preflight(plan, definition), [plan, definition]);

    /** The sector a write clears, and how far past the calibration body it reaches. */
    const erase = useMemo(() => {
        const sector = calibrationSector(plan.original);
        if (!sector) return null;
        return { sector, ...collateralOf(sector, CALIBRATION_LO, CALIBRATION_HI) };
    }, [plan.original]);
    const findings = result.ok ? result.notes : result.findings;
    const blocking = findings.filter(f => f.severity === 'blocking');
    const passed = CHECKS.filter(id => !findings.some(f => f.id === id));

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
            <div className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm" onClick={onClose} />
            {/* 618 x 382: φ, same as every other window here. */}
            <div className="relative flex max-h-full w-full max-w-[618px] flex-col rounded-lg border border-slate-800 bg-slate-900 shadow-xl">
                <div className="flex h-[44px] flex-none items-center gap-3 border-b border-slate-800 px-4">
                    {blocking.length > 0
                        ? <ShieldAlert className="size-4 text-red-400" />
                        : <ShieldCheck className="size-4 text-emerald-400" />}
                    <span className={`${LABEL} text-slate-300`}>{C.flashPreflight}</span>
                    <Pill tone={blocking.length > 0 ? 'caution' : 'ok'}>
                        {blocking.length > 0 ? C.blocked : C.passed}
                    </Pill>
                    <button onClick={onClose} aria-label={C.close} className="ml-auto text-slate-500 transition hover:text-slate-300">
                        <X className="size-4" />
                    </button>
                </div>

                <div className="min-h-0 flex-1 space-y-4 overflow-y-auto p-4">
                    <p className="text-[11px] leading-relaxed text-slate-400">{t.flashIntro}</p>

                    {/* What would actually be cleared. A confirmation that cannot state this is
                        not a confirmation, and until the ECU's erase table was read this pane had
                        nothing to put here. */}
                    {erase && (
                        <div>
                            <MicroLabel>{C.whatGetsErased}</MicroLabel>
                            <p className="font-mono text-[11px] text-slate-300">
                                0x{erase.sector.start.toString(16).toUpperCase()}
                                {' – '}
                                0x{(erase.sector.end - 1).toString(16).toUpperCase()}
                                <span className="ml-2 text-slate-500">
                                    {((erase.sector.end - erase.sector.start) / 1024).toFixed(0)} KiB
                                </span>
                            </p>
                            <p className="mt-1 text-[11px] leading-relaxed text-slate-500">
                                {t.eraseCollateral(erase.below, erase.above)}
                            </p>
                        </div>
                    )}

                    <div>
                        <MicroLabel>{C.checksRun}</MicroLabel>
                        <p className="font-mono text-[10px] leading-relaxed text-slate-500">
                            {passed.length > 0 ? passed.join('  ·  ') : '-'}
                        </p>
                    </div>

                    <div>
                        <MicroLabel>{C.whatStopsIt}</MicroLabel>
                        {findings.length === 0 ? (
                            <p className="text-[11px] text-slate-500">-</p>
                        ) : (
                            <ul className="space-y-2">
                                {findings.map(f => (
                                    <li key={f.id} className="border-l-2 border-slate-800 pl-3">
                                        <div className="flex items-baseline gap-2">
                                            <span className="font-mono text-[10px] text-slate-400">{f.id}</span>
                                            <Pill tone={f.severity === 'blocking' ? 'caution' : 'secondary'}>
                                                {f.severity === 'blocking' ? C.blocking : C.note}
                                            </Pill>
                                        </div>
                                        <p className="mt-0.5 text-[11px] leading-relaxed text-slate-300">{f.detail}</p>
                                        <p className="mt-0.5 text-[10px] leading-relaxed text-slate-500">→ {f.next}</p>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </div>
                </div>

                <div className="flex h-[52px] flex-none items-center justify-end gap-6 border-t border-slate-800 px-4">
                    <TextButton tone="neutral" onClick={onClose}>{C.close}</TextButton>
                    {/*
                        Deliberately not a disabled-looking button that might one day be enabled by
                        a stray prop. There is no write control in this build at all: the package
                        that could build one is not imported here, and `preflight` has never
                        returned `ok` against a real plan. What the operator gets is the reason.
                    */}
                    <span className={`${LABEL} text-slate-600`}>{C.noWritePath}</span>
                </div>
            </div>
        </div>
    );
}

/** The CRC-protected calibration body, per `docs/full-image-analysis.md` §5.2. */
const CALIBRATION_LO = 0x320e0;
const CALIBRATION_HI = 0x378c0;

/** The checks `preflight` runs, so the ones that passed can be named rather than merely absent. */
const CHECKS = [
    'length', 'zb-unknown', 'zb-not-declared', 'zb-mismatch', 'checksum', 'backup',
    'battery-unknown', 'battery-low', 'unclaimed-bytes', 'unnamed-edit', 'erase-granularity',
] as const;
